name: Deployment Develop
on:
  push:
    branches:
      - master
jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing commands in remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          cd www/nuxt-content-video 
          ls -al
          git pull origin master
          git fetch && git checkout master
          npm install
          npm run build
