name: remote ssh command
on:
  push:
    branches:
      - master
jobs: 

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      env:
        DEV: development
        CI_EMAIL: "passionatebot@passionatepeople.io"
        CI_USERNAME: ""
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: DEV
        script: |
          whoami
          echo $DEV
          cd www/nuxt-content-video
          ls -al
          git fetch && git checkout master
          git pull
          npm install
          npm run build

